ADVERTISE_APP/ADVERTISE_APP/urls.py
from .views import *
from ADVERTISE_APP import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('Header/', BehindHeader.as_view(), name='Header'),
    path('Footer/', BehindFooter.as_view(), name='Footer'),
    path('', include('advertiser_management.urls', namespace='advertise')),
    path('', Home.as_view(), name='Home'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ADVERTISE_APP/advertiser_management/urls.py
from rest_framework.routers import DefaultRouter

from .views import *
from django.urls import path, include

app_name = 'advertise'

router = DefaultRouter()
router.register(r'advertiser', AdvertiserView, basename='advertiser')
router.register(r'ad', AdView, basename='ad')

urlpatterns = [
    path('', include(router.urls)),
    path(r'login', LoginAPIView.as_view(), name='login'),
    path(r'logout', LogoutAPIView.as_view(), name='logout'),
]

ADVERTISE_APP/advertiser_management/models.py
from django.db import models
from django.contrib.auth.models import User


class BaseAdvertise(models.Model):
    active = models.BooleanField(default=True)

    class Meta:
        abstract = True


class Advertiser(BaseAdvertise):
    user = models.OneToOneField(User, related_name='advertiser', on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Advertiser"
        ordering = ['id']


class Ad(BaseAdvertise):
    advertiser = models.ForeignKey(Advertiser, related_name='ads', on_delete=models.CASCADE)
    title = models.CharField(max_length=30)
    approve = models.BooleanField(default=False)
    linkUrl = models.URLField(max_length=2000)
    img_Url = models.URLField(max_length=2000)
    description = models.TextField()

    class Meta:
        verbose_name = "Advertise"


class BaseVisiting(models.Model):
    time = models.DateTimeField(auto_now_add=True)
    ip = models.GenericIPAddressField()

    class Meta:
        abstract = True


class ViewAd(BaseVisiting):
    ad = models.ForeignKey(Ad, related_name='views', on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Ad View"


class ClickAd(BaseVisiting):
    ad = models.ForeignKey(Ad, related_name='clicks', on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Ad Click"


class Report(models.Model):
    number_of_clicks = models.IntegerField()
    number_of_views = models.IntegerField()
    time = models.DateTimeField(auto_now_add=True)
    type = models.CharField(max_length=100)

    class Meta:
        verbose_name = 'Report'

ADVERTISE_APP/ADVERTISE_APP/views.py
from django.views.generic import TemplateView, RedirectView
from django.shortcuts import render


class BehindHeader(TemplateView):
    template_name = 'shared/_Header.html'

    def post(self, request, **kwargs):
        return render(request, self.template_name)


class BehindFooter(TemplateView):
    template_name = 'shared/_Footer.html'

    def post(self, request, **kwargs):
        return render(request, self.template_name)


class Home(RedirectView):
    url = '/advertiserList'

ADVERTISE_APP/advertiser_management/views.py
from django.contrib.auth import login, logout
from django.db.models.functions import ExtractHour
from django.views.generic import RedirectView
from django.db.models import Count
from rest_framework.authentication import TokenAuthentication

from rest_framework.authtoken.models import Token
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.status import HTTP_200_OK

from advertiser_management.serializers import *
from rest_framework.viewsets import *
from rest_framework.generics import *
from .models import *


# Create your views here.
from .permissions import IsAdvertiser, NotAuthentication


class AdvertiserView(ModelViewSet):
    queryset = Advertiser.objects.filter(active=True)
    serializer_class = AdvertiserSerializer

    def get(self, request, pk=None):
        if pk:
            return self.retrieve(request, pk)
        else:
            return self.list(request)

    class Meta:
        model = Advertiser


class AdView(ModelViewSet):
    queryset = Ad.objects.filter(active=True, approve=True)
    serializer_class = AdvertiseSerializer

    @staticmethod
    def clicks_per_hour(obj):
        return obj.clicks.annotate(hour=ExtractHour('time')).values('hour') \
            .annotate(count=Count('hour')).values('hour', 'count')

    @staticmethod
    def views_per_hour(obj):
        return obj.views.annotate(hour=ExtractHour('time')).values('hour') \
            .annotate(count=Count('hour'))

    def get(self, request, pk=None):
        if pk:
            return self.retrieve(request, pk)
        else:
            return self.list(request)

    def retrieve(self, request, *args, **kwargs):
        result = super(AdView, self).retrieve(request, *args, **kwargs)
        result.data['clicks_per_hour'] = self.clicks_per_hour(self.get_object())
        result.data['views_per_hour'] = self.views_per_hour(self.get_object())
        return result

    class Meta:
        model = Ad


class LoginAPIView(GenericAPIView):
    serializer_class = UserSerializer
    permission_classes = [NotAuthentication]

    @staticmethod
    def post(request):
        user = get_object_or_404(
            User,
            username=request.data['username'],
            password=request.data['password'],
        )
        token, created = Token.objects.get_or_create(user=user)
        login(request, token.user)
        return Response(data={'auth_token': token.key}, status=HTTP_200_OK)


class LogoutAPIView(GenericAPIView):

    @staticmethod
    def get(request):
        logout(request)
        return Response(status=HTTP_200_OK)


class ClickRedirect(RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        ad = Ad.objects.get(id=kwargs['pk'])
        ad.click(self.request.ip)
        return ad.link

ADVERTISE_APP/templates/shared/_Footer.html
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active" aria-current="page"> The END :) </li>
  </ol>
</nav>

ADVERTISE_APP/templates/shared/_Footer_Reference.html
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

ADVERTISE_APP/templates/shared/_Header.html
{% url 'advertise:advertiser-register' as register_url %}
{% url 'advertise:logout' as logout_url %}
{% url 'advertise:login' as login_url %}
{% url 'advertise:advertiser-list' as list_url %}
{% url 'advertise:ad-create' as create_ad_url %}


<div class="pos-f-t">
    <div class="collapse" id="navbarToggleExternalContent">
        <div class="bg-dark p-4">
            <h5 class="text-white h4">Welcome to my Miny Site :)</h5>
            <div class="navbar-collapse">
                <ul class="nav navbar-nav navbar-left">

                    <li><a href="{{ list_url }}">Advertiser List</a></li>
                    <li><a href="{{ register_url }}">Register Advertiser</a></li>

                    {% if request.user.is_authenticated %}
                        <li><a href="{{ create_ad_url }}">Create new Advertise</a></li>
                        <li><a href="{{ logout_url }}">Log out</a></li>
                    {% else %}
                        <li><a href="{{ login_url }}">Login</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
    <nav class="navbar navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarToggleExternalContent"
                aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </nav>
</div>

ADVERTISE_APP/templates/shared/_Header_Reference.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

ADVERTISE_APP/templates/shared/_MainLayout.html
{% load static %}
{% load render_partial %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    {% include 'shared/_Header_Reference.html' %}
    <title> GOOD GOODS FOR GOOD MEN </title>
    {% block header_ref %}{% endblock %}
</head>
<body>
{% render_partial 'Header' %}
{% block content %}{% endblock %}
{% render_partial 'Footer' %}
{% block footer_ref %}{% endblock %}
{% include 'shared/_Footer_Reference.html' %}
</body>
</html>